"""Add priority field to tasks

Revision ID: 8f09b42702fa
Revises: 001
Create Date: 2025-12-19 12:26:20.050838

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8f09b42702fa'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.drop_index('ix_tasks_user_id_completed', table_name='tasks')
    op.drop_constraint('tasks_user_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_user_id_fkey', 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_tasks_user_id_completed', 'tasks', ['user_id', 'completed'], unique=False)
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
